/* Generated by re2c 0.14.3 on Wed Aug  4 15:58:01 2021 */
#line 1 "inc/ptx_parser.hre"
#ifndef PTX_PARSER_H
#define PTX_PARSER_H

#include "PTXFunction.h"

#include <fstream>
#include <iostream>
#include <istream>
#include <map>
#include <regex>
#include <string>
#include <vector>

namespace mekong {

#define YYMAXFILL 13

struct input_t {
  size_t len;
  char *str;

  input_t(const char *s) : len(strlen(s)), str(new char[len + YYMAXFILL]) {
    memcpy(str, s, len);
    memset(str + len, ' ', YYMAXFILL);
  }
  ~input_t() { delete[] str; }
};

enum TokenClass {
  None,
  Comment,
  Directive,
  Identifier,
  Integer,
  Float,
  lBracket,
  rBracket,
  lcBracket,
  rcBracket,
  leBracket,
  reBracket,
  Register,
  Comma,
  Semicolon,
  Guard,
  Instruction,
  Label,
  AddressOp,
  EqualSign,
  String,
  Separator
};

const char *TokenClassName[] = {
    "None",      "Comment",     "Directive", "Identifier", "Integer",
    "Float",     "lBracket",    "rBracket",  "lcBracket",  "rcBracket",
    "leBracket", "reBracket",   "Register",  "Comma",      "Semicolon",
    "Guard",     "Instruction", "Label",     "AddressOp",  "EqualSign",
    "String",	 "Separator"};

struct Token {
  TokenClass ty = None;
  std::string str;

  Token(TokenClass tc, std::string str) : ty(tc), str(str){};
};

std::vector<Token> lexicalAnalysis(std::string filename) {
  std::vector<Token> tokenVec;
  std::ifstream file(filename, std::ios::binary | std::ios::ate);
  auto size = file.tellg();
  file.seekg(0, std::ios::beg);

  std::string buffer(size, '\0');
  if (!file.read(&buffer[0], size))
    return tokenVec;

  auto addToken = [&tokenVec](TokenClass ty, const char *const begin = nullptr,
                              const char *const end = nullptr) {
    if (begin == nullptr or end == nullptr)
      tokenVec.push_back({ty, ""});
    tokenVec.push_back({ty, std::string(begin, end - begin)});
  };

  input_t input(buffer.c_str());
  const char *YYCURSOR = input.str;
  const char *const YYLIMIT = input.str + input.len + YYMAXFILL;
  const char *YYMARKER = YYLIMIT;

  for (;;) {
    const char *token = YYCURSOR;
    
#line 96 "inc/ptx_parser.h"
{
	char yych;
	unsigned int yyaccept = 0;

	if ((YYLIMIT - YYCURSOR) < 13) break;
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case '\n':
	case '\v':
	case '\r':
	case ' ':	goto yy4;
	case '"':	goto yy6;
	case '$':
	case '_':	goto yy7;
	case '%':	goto yy8;
	case '\'':	goto yy9;
	case '(':	goto yy10;
	case ')':	goto yy12;
	case '+':	goto yy14;
	case ',':	goto yy16;
	case '-':	goto yy18;
	case '.':	goto yy20;
	case '/':	goto yy22;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy23;
	case ';':	goto yy25;
	case '=':	goto yy27;
	case '@':	goto yy29;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':	goto yy31;
	case '[':	goto yy33;
	case ']':	goto yy35;
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy37;
	case '{':	goto yy39;
	case '|':	goto yy41;
	case '}':	goto yy43;
	default:	goto yy2;
	}
yy2:
	++YYCURSOR;
yy3:
#line 98 "inc/ptx_parser.hre"
	{ std::cerr << "no match:\t" << std::string(token, YYCURSOR-token) <<
      "\n"; continue;}
#line 199 "inc/ptx_parser.h"
yy4:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	goto yy78;
yy5:
#line 104 "inc/ptx_parser.hre"
	{ continue; }
#line 207 "inc/ptx_parser.h"
yy6:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	goto yy188;
yy7:
	yych = *++YYCURSOR;
	switch (yych) {
	case '$':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy159;
	default:	goto yy3;
	}
yy8:
	yych = *++YYCURSOR;
	switch (yych) {
	case '$':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':	goto yy159;
	case 'a':
	case 'b':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy161;
	case 'c':	goto yy163;
	case 'n':	goto yy164;
	case 't':	goto yy165;
	default:	goto yy3;
	}
yy9:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	goto yy156;
yy10:
	++YYCURSOR;
#line 123 "inc/ptx_parser.hre"
	{ addToken(lBracket, token, YYCURSOR); continue;}
#line 358 "inc/ptx_parser.h"
yy12:
	++YYCURSOR;
#line 124 "inc/ptx_parser.hre"
	{ addToken(rBracket, token, YYCURSOR); continue;}
#line 363 "inc/ptx_parser.h"
yy14:
	++YYCURSOR;
#line 139 "inc/ptx_parser.hre"
	{ addToken(AddressOp, token, YYCURSOR); continue;}
#line 368 "inc/ptx_parser.h"
yy16:
	++YYCURSOR;
#line 131 "inc/ptx_parser.hre"
	{ addToken(Comma, token, YYCURSOR); continue;}
#line 373 "inc/ptx_parser.h"
yy18:
	++YYCURSOR;
#line 140 "inc/ptx_parser.hre"
	{ addToken(AddressOp, token, YYCURSOR); continue;}
#line 378 "inc/ptx_parser.h"
yy20:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy61;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'c':
	case 'd':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'm':
	case 'n':
	case 'o':
	case 'q':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy83;
	case 'a':	goto yy85;
	case 'b':
	case 'f':
	case 's':
	case 'u':	goto yy82;
	case 'e':	goto yy86;
	case 'g':	goto yy87;
	case 'l':	goto yy88;
	case 'p':	goto yy89;
	case 'r':	goto yy90;
	case 't':	goto yy91;
	case 'v':	goto yy92;
	default:	goto yy21;
	}
yy21:
#line 119 "inc/ptx_parser.hre"
	{ addToken(Directive, token, YYCURSOR); continue;}
#line 449 "inc/ptx_parser.h"
yy22:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '*':	goto yy74;
	case '/':	goto yy72;
	default:	goto yy3;
	}
yy23:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '.':	goto yy61;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy59;
	case 'E':
	case 'e':	goto yy58;
	default:	goto yy24;
	}
yy24:
#line 173 "inc/ptx_parser.hre"
	{ addToken(Integer, token, YYCURSOR); continue;}
#line 480 "inc/ptx_parser.h"
yy25:
	++YYCURSOR;
#line 133 "inc/ptx_parser.hre"
	{ addToken(Semicolon, token, YYCURSOR); continue;}
#line 485 "inc/ptx_parser.h"
yy27:
	++YYCURSOR;
#line 136 "inc/ptx_parser.hre"
	{ addToken(EqualSign, token, YYCURSOR); continue;}
#line 490 "inc/ptx_parser.h"
yy29:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '!':	goto yy57;
	default:	goto yy30;
	}
yy30:
#line 158 "inc/ptx_parser.hre"
	{ addToken(Guard, token, YYCURSOR); continue;}
#line 500 "inc/ptx_parser.h"
yy31:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy46;
yy32:
#line 167 "inc/ptx_parser.hre"
	{ addToken(Identifier, token, YYCURSOR); continue;}
#line 508 "inc/ptx_parser.h"
yy33:
	++YYCURSOR;
#line 125 "inc/ptx_parser.hre"
	{ addToken(leBracket, token, YYCURSOR); continue;}
#line 513 "inc/ptx_parser.h"
yy35:
	++YYCURSOR;
#line 126 "inc/ptx_parser.hre"
	{ addToken(reBracket, token, YYCURSOR); continue;}
#line 518 "inc/ptx_parser.h"
yy37:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '$':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':	goto yy45;
	case '.':	goto yy53;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy47;
	case ':':	goto yy51;
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy49;
	default:	goto yy38;
	}
yy38:
#line 161 "inc/ptx_parser.hre"
	{ addToken(Instruction, token, YYCURSOR);
      continue;}
#line 595 "inc/ptx_parser.h"
yy39:
	++YYCURSOR;
#line 127 "inc/ptx_parser.hre"
	{ addToken(lcBracket, token, YYCURSOR); continue;}
#line 600 "inc/ptx_parser.h"
yy41:
	++YYCURSOR;
#line 155 "inc/ptx_parser.hre"
	{ addToken(Separator, token, YYCURSOR); continue;}
#line 605 "inc/ptx_parser.h"
yy43:
	++YYCURSOR;
#line 128 "inc/ptx_parser.hre"
	{ addToken(rcBracket, token, YYCURSOR); continue;}
#line 610 "inc/ptx_parser.h"
yy45:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) break;
	yych = *YYCURSOR;
yy46:
	switch (yych) {
	case '$':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy45;
	case ':':	goto yy51;
	default:	goto yy32;
	}
yy47:
	yyaccept = 3;
	YYMARKER = ++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) break;
	yych = *YYCURSOR;
	switch (yych) {
	case '$':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':	goto yy45;
	case '.':	goto yy53;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy47;
	case ':':	goto yy51;
	default:	goto yy38;
	}
yy49:
	yyaccept = 3;
	YYMARKER = ++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) break;
	yych = *YYCURSOR;
	switch (yych) {
	case '$':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':	goto yy45;
	case '.':	goto yy53;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy47;
	case ':':	goto yy51;
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy49;
	default:	goto yy38;
	}
yy51:
	++YYCURSOR;
#line 170 "inc/ptx_parser.hre"
	{ addToken(Label, token, YYCURSOR); continue;}
#line 836 "inc/ptx_parser.h"
yy53:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) break;
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy55;
	default:	goto yy54;
	}
yy54:
	YYCURSOR = YYMARKER;
	switch (yyaccept) {
	case 0: 	goto yy5;
	case 1: 	goto yy3;
	case 2: 	goto yy24;
	case 3: 	goto yy38;
	case 4: 	goto yy63;
	case 5: 	goto yy21;
	default:	goto yy32;
	}
yy55:
	yyaccept = 3;
	YYMARKER = ++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) break;
	yych = *YYCURSOR;
	switch (yych) {
	case '.':	goto yy53;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy55;
	default:	goto yy38;
	}
yy57:
	yych = *++YYCURSOR;
	goto yy30;
yy58:
	yych = *++YYCURSOR;
	switch (yych) {
	case '+':
	case '-':	goto yy69;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy70;
	default:	goto yy54;
	}
yy59:
	yyaccept = 2;
	YYMARKER = ++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 3) break;
	yych = *YYCURSOR;
	switch (yych) {
	case '.':	goto yy61;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy59;
	case 'E':
	case 'e':	goto yy58;
	default:	goto yy24;
	}
yy61:
	yyaccept = 4;
	YYMARKER = ++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 3) break;
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy61;
	case 'E':
	case 'e':	goto yy64;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy65;
	default:	goto yy63;
	}
yy63:
#line 179 "inc/ptx_parser.hre"
	{ addToken(Float, token, YYCURSOR); continue;}
#line 1004 "inc/ptx_parser.h"
yy64:
	yych = *++YYCURSOR;
	switch (yych) {
	case '+':
	case '-':	goto yy66;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy67;
	default:	goto yy54;
	}
yy65:
	yych = *++YYCURSOR;
	goto yy63;
yy66:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy67;
	default:	goto yy54;
	}
yy67:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) break;
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy67;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy65;
	default:	goto yy63;
	}
yy69:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy70;
	default:	goto yy54;
	}
yy70:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) break;
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy70;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy65;
	default:	goto yy63;
	}
yy72:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) break;
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':	goto yy80;
	default:	goto yy72;
	}
yy74:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) break;
	yych = *YYCURSOR;
	switch (yych) {
	case '*':	goto yy76;
	default:	goto yy74;
	}
yy76:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) break;
	yych = *YYCURSOR;
	switch (yych) {
	case '/':	goto yy77;
	default:	goto yy74;
	}
yy77:
	yyaccept = 0;
	YYMARKER = ++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) break;
	yych = *YYCURSOR;
yy78:
	switch (yych) {
	case '\t':
	case '\n':
	case '\v':
	case '\r':
	case ' ':	goto yy77;
	case '/':	goto yy79;
	default:	goto yy5;
	}
yy79:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) break;
	yych = *YYCURSOR;
	switch (yych) {
	case '*':	goto yy74;
	default:	goto yy54;
	}
yy80:
	++YYCURSOR;
#line 106 "inc/ptx_parser.hre"
	{ addToken(Comment, token, YYCURSOR); continue;}
#line 1148 "inc/ptx_parser.h"
yy82:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '3':	goto yy151;
	case '6':	goto yy152;
	default:	goto yy84;
	}
yy83:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) break;
	yych = *YYCURSOR;
yy84:
	switch (yych) {
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy83;
	default:	goto yy21;
	}
yy85:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy139;
	default:	goto yy84;
	}
yy86:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy134;
	default:	goto yy84;
	}
yy87:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy128;
	default:	goto yy84;
	}
yy88:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy125;
	default:	goto yy84;
	}
yy89:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy116;
	case 'r':	goto yy117;
	default:	goto yy84;
	}
yy90:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy113;
	default:	goto yy84;
	}
yy91:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy107;
	default:	goto yy84;
	}
yy92:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy93;
	case 'i':	goto yy94;
	default:	goto yy84;
	}
yy93:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy101;
	default:	goto yy84;
	}
yy94:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy95;
	default:	goto yy84;
	}
yy95:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy96;
	default:	goto yy84;
	}
yy96:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'b':	goto yy97;
	default:	goto yy84;
	}
yy97:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy98;
	default:	goto yy84;
	}
yy98:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy99;
	default:	goto yy84;
	}
yy99:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy83;
	default:	goto yy100;
	}
yy100:
#line 112 "inc/ptx_parser.hre"
	{ addToken(Directive, token, YYCURSOR); continue;}
#line 1363 "inc/ptx_parser.h"
yy101:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy102;
	default:	goto yy84;
	}
yy102:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy103;
	default:	goto yy84;
	}
yy103:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy104;
	default:	goto yy84;
	}
yy104:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy105;
	default:	goto yy84;
	}
yy105:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy83;
	default:	goto yy106;
	}
yy106:
#line 109 "inc/ptx_parser.hre"
	{ addToken(Directive, token, YYCURSOR); continue;}
#line 1448 "inc/ptx_parser.h"
yy107:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy108;
	default:	goto yy84;
	}
yy108:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy109;
	default:	goto yy84;
	}
yy109:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy110;
	default:	goto yy84;
	}
yy110:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy111;
	default:	goto yy84;
	}
yy111:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy83;
	default:	goto yy112;
	}
yy112:
#line 110 "inc/ptx_parser.hre"
	{ addToken(Directive, token, YYCURSOR); continue;}
#line 1533 "inc/ptx_parser.h"
yy113:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy114;
	default:	goto yy84;
	}
yy114:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy83;
	default:	goto yy115;
	}
yy115:
#line 115 "inc/ptx_parser.hre"
	{ addToken(Directive, token, YYCURSOR); continue;}
#line 1600 "inc/ptx_parser.h"
yy116:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy121;
	default:	goto yy84;
	}
yy117:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy118;
	default:	goto yy84;
	}
yy118:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy119;
	default:	goto yy84;
	}
yy119:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy83;
	default:	goto yy120;
	}
yy120:
#line 116 "inc/ptx_parser.hre"
	{ addToken(Directive, token, YYCURSOR); continue;}
#line 1679 "inc/ptx_parser.h"
yy121:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy122;
	default:	goto yy84;
	}
yy122:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy123;
	default:	goto yy84;
	}
yy123:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy83;
	default:	goto yy124;
	}
yy124:
#line 114 "inc/ptx_parser.hre"
	{ addToken(Directive, token, YYCURSOR); continue;}
#line 1752 "inc/ptx_parser.h"
yy125:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy126;
	default:	goto yy84;
	}
yy126:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy83;
	default:	goto yy127;
	}
yy127:
#line 118 "inc/ptx_parser.hre"
	{ addToken(Directive, token, YYCURSOR); continue;}
#line 1819 "inc/ptx_parser.h"
yy128:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy129;
	default:	goto yy84;
	}
yy129:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'b':	goto yy130;
	default:	goto yy84;
	}
yy130:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy131;
	default:	goto yy84;
	}
yy131:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy132;
	default:	goto yy84;
	}
yy132:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy83;
	default:	goto yy133;
	}
yy133:
#line 117 "inc/ptx_parser.hre"
	{ addToken(Directive, token, YYCURSOR); continue;}
#line 1904 "inc/ptx_parser.h"
yy134:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy135;
	default:	goto yy84;
	}
yy135:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy136;
	default:	goto yy84;
	}
yy136:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'y':	goto yy137;
	default:	goto yy84;
	}
yy137:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy83;
	default:	goto yy138;
	}
yy138:
#line 113 "inc/ptx_parser.hre"
	{ addToken(Directive, token, YYCURSOR); continue;}
#line 1983 "inc/ptx_parser.h"
yy139:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy140;
	default:	goto yy84;
	}
yy140:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy141;
	default:	goto yy84;
	}
yy141:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy142;
	default:	goto yy84;
	}
yy142:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy143;
	default:	goto yy84;
	}
yy143:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy144;
	default:	goto yy84;
	}
yy144:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '_':	goto yy145;
	default:	goto yy84;
	}
yy145:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy146;
	default:	goto yy54;
	}
yy146:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy147;
	default:	goto yy54;
	}
yy147:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'z':	goto yy148;
	default:	goto yy54;
	}
yy148:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy149;
	default:	goto yy54;
	}
yy149:
	++YYCURSOR;
#line 111 "inc/ptx_parser.hre"
	{ addToken(Directive, token, YYCURSOR); continue;}
#line 2049 "inc/ptx_parser.h"
yy151:
	yych = *++YYCURSOR;
	switch (yych) {
	case '2':	goto yy153;
	default:	goto yy54;
	}
yy152:
	yych = *++YYCURSOR;
	switch (yych) {
	case '4':	goto yy153;
	default:	goto yy54;
	}
yy153:
	++YYCURSOR;
#line 120 "inc/ptx_parser.hre"
	{ addToken(Directive, token, YYCURSOR); continue;}
#line 2066 "inc/ptx_parser.h"
yy155:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) break;
	yych = *YYCURSOR;
yy156:
	switch (yych) {
	case '\'':	goto yy157;
	default:	goto yy155;
	}
yy157:
	++YYCURSOR;
#line 147 "inc/ptx_parser.hre"
	{ addToken(String, token, YYCURSOR); continue;}
#line 2080 "inc/ptx_parser.h"
yy159:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) break;
	yych = *YYCURSOR;
yy160:
	switch (yych) {
	case '$':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy159;
	case ':':	goto yy51;
	default:	goto yy32;
	}
yy161:
	yyaccept = 6;
	YYMARKER = ++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 2) break;
	yych = *YYCURSOR;
	switch (yych) {
	case '$':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':	goto yy159;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy167;
	case ':':	goto yy51;
	case '<':	goto yy166;
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy161;
	default:	goto yy32;
	}
yy163:
	yyaccept = 6;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy167;
	case '<':	goto yy166;
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy161;
	case 't':	goto yy184;
	default:	goto yy160;
	}
yy164:
	yyaccept = 6;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy167;
	case '<':	goto yy166;
	case 'a':
	case 'b':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy161;
	case 'c':	goto yy178;
	case 't':	goto yy179;
	default:	goto yy160;
	}
yy165:
	yyaccept = 6;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy167;
	case '<':	goto yy166;
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy161;
	case 'i':	goto yy170;
	default:	goto yy160;
	}
yy166:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy176;
	default:	goto yy54;
	}
yy167:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) break;
	yych = *YYCURSOR;
	switch (yych) {
	case '$':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy159;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy167;
	case ':':	goto yy51;
	case '>':	goto yy175;
	default:	goto yy169;
	}
yy169:
#line 150 "inc/ptx_parser.hre"
	{ addToken(Register, token, YYCURSOR); continue;}
#line 2448 "inc/ptx_parser.h"
yy170:
	yyaccept = 6;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy167;
	case '<':	goto yy166;
	case 'a':
	case 'b':
	case 'c':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy161;
	case 'd':	goto yy171;
	default:	goto yy160;
	}
yy171:
	yyaccept = 6;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '.':	goto yy172;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy167;
	case '<':	goto yy166;
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy161;
	default:	goto yy160;
	}
yy172:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'x':
	case 'y':
	case 'z':	goto yy173;
	default:	goto yy54;
	}
yy173:
	++YYCURSOR;
#line 152 "inc/ptx_parser.hre"
	{ addToken(Register, token,
      YYCURSOR); continue;}
#line 2549 "inc/ptx_parser.h"
yy175:
	yych = *++YYCURSOR;
	goto yy169;
yy176:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) break;
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy176;
	case '>':	goto yy175;
	default:	goto yy169;
	}
yy178:
	yyaccept = 6;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy167;
	case '<':	goto yy166;
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy161;
	case 't':	goto yy181;
	default:	goto yy160;
	}
yy179:
	yyaccept = 6;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy167;
	case '<':	goto yy166;
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy161;
	case 'i':	goto yy180;
	default:	goto yy160;
	}
yy180:
	yyaccept = 6;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy167;
	case '<':	goto yy166;
	case 'a':
	case 'b':
	case 'c':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy161;
	case 'd':	goto yy171;
	default:	goto yy160;
	}
yy181:
	yyaccept = 6;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy167;
	case '<':	goto yy166;
	case 'a':	goto yy182;
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy161;
	default:	goto yy160;
	}
yy182:
	yyaccept = 6;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy167;
	case '<':	goto yy166;
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy161;
	case 'i':	goto yy183;
	default:	goto yy160;
	}
yy183:
	yyaccept = 6;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy167;
	case '<':	goto yy166;
	case 'a':
	case 'b':
	case 'c':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy161;
	case 'd':	goto yy171;
	default:	goto yy160;
	}
yy184:
	yyaccept = 6;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy167;
	case '<':	goto yy166;
	case 'a':	goto yy185;
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy161;
	default:	goto yy160;
	}
yy185:
	yyaccept = 6;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy167;
	case '<':	goto yy166;
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy161;
	case 'i':	goto yy186;
	default:	goto yy160;
	}
yy186:
	yyaccept = 6;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy167;
	case '<':	goto yy166;
	case 'a':
	case 'b':
	case 'c':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy161;
	case 'd':	goto yy171;
	default:	goto yy160;
	}
yy187:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) break;
	yych = *YYCURSOR;
yy188:
	switch (yych) {
	case '"':	goto yy157;
	default:	goto yy187;
	}
}
#line 181 "inc/ptx_parser.hre"

    if (YYCURSOR >= YYLIMIT)
      break;
  }

  // for (auto token : tokenVec){
  //  std::cout << TokenClassName[token.ty] << ": " << token.str << '\n';
  //}

  return tokenVec;
}

// Parsing
// * .entry .* _kernel_name_ [(parameter+)] { statement+ }
// statement: .directive+ operand+;
//            instruction operand+;
// operand: register  | string | int | float | address

enum TokenQuantizer { TQ_None, One, LeastOne, Any };

bool parseFunction(std::vector<Token>::iterator iter,
                   std::vector<Token>::iterator end, PTXFunction &func) {

  Token next = *(iter);
  // Get FunctionName
  do {
    next = *(iter++);
    switch (next.ty) {
    case lBracket:
      do { // Skip all tokens until bracket is closed
        next = *(iter++);
      } while (next.ty != rBracket);
      break;
    case Identifier:
      func.name = next.str; // Found Function Name
      break;
    default:
      break; // Skip Token
    }
  } while (next.ty != Identifier);

  // Check for Parameterlist
  if (next.ty == lBracket) {
    do {
      next = *(iter++);
    } while (next.ty != rBracket);
    next = *(iter++);
  }

  // Check for Function Body
  bool forever = true;
  do {
    switch (next.ty) {
    case lcBracket:
      forever = false;
      break; // Found function body
    case Semicolon:
      return true; // Found function decleration
    default:
      next = *(iter++);
    }
  } while (forever);

  if (next.ty == lcBracket) {
    std::string currentBB = "";
    int bbIdx = -1;
    int cBracketLevel = 0;

    do {
      next = *(iter++);

      // Directive?
      if (next.ty == Directive) {
        // If .loc directive, skip the next 3 integers
        if (next.str == ".loc") {
          for (int i = 0; i < 3; ++i) {
            next = *(iter++);
            if (next.ty != Integer)
              std::cerr << "ERROR: Expected Integer, got "
                        << TokenClassName[next.ty] << " instead\n";
          }
        } else {
          // Skip until Semicolon
          do {
            next = *(iter++);
          } while (next.ty != Semicolon);
        }
      }
      // Instruction
      else if (next.ty == Instruction) {
        if (currentBB.empty() or bbIdx < 0) {
          std::cerr << "No BB to assign instruction!\n";
          std::cerr << "Instruction: " << next.str << "\n";
          return false;
        }

	int flag = 0;
	std::string temp = next.str;
        //func.bb[bbIdx].inst.push_back(next.str);
        // Skip until Semicolon
        do {
          next = *(iter++);
	  if(next.ty != Comma && next.ty != Semicolon){
		if(next.ty == reBracket || next.ty == AddressOp || flag==1){
                        if(next.ty == Register){
				temp = temp + ".." + next.str + "..";
			} else {
				temp = temp + next.str;
			}
                } else {
                        temp = temp + " " + next.str;
                }	
		if(next.ty == leBracket){
			flag = 1;
		}
		if(next.ty == reBracket){
                	flag = 0;
             	}
	  }
        } while (next.ty != Semicolon);
	func.bb[bbIdx].inst.push_back(temp);
      }
      // Comment
      else if (next.ty == Comment) {
        // Check for BB Label
        size_t pos = next.str.rfind("// %");
        if (pos != std::string::npos) {
          size_t bbPos = pos + 4;
          // Check for whitespace and colon after name
          // use this as end of the bb label
          size_t wpos1 = next.str.find(" ", bbPos);
          size_t wpos2 = next.str.find("\t", bbPos);
          size_t wpos3 = next.str.find(":", bbPos);
          size_t wpos = wpos1 < wpos2 ? wpos1 : wpos2;
          wpos = wpos < wpos3 ? wpos : wpos3;
          size_t len;
          if (wpos != std::string::npos)
            len = wpos - (bbPos);
          else
            len = next.str.rfind("\n") - (bbPos);

          currentBB = next.str.substr(bbPos, len);
          func.bb.push_back({currentBB, {}});
          ++bbIdx;
          // std::cout << "Found BB: " << currentBB << '\n';
        }
      }
      // Label
      else if (next.ty == Label) {
        // Skip
      }
      // Guard
      else if (next.ty == Guard) {
        // Skip
        next = *(iter++);
	std::string p ("p");
	if(next.str.compare(p) == 0){
	  // Skip
	//do {
		// Skip
		next = *(iter++);
		break;
	}
	//} while (next.ty != Semicolon);
	/*
	if ((*(iter)).ty == Instruction){
	  next = *(iter);
	  if (currentBB.empty() or bbIdx < 0) {
            std::cerr << "No BB to assign instruction!\n";
            std::cerr << "Instruction: " << next.str << "\n";
            return false;
          }

          int flag = 0;
          std::string temp = next.str;
          // Skip until Semicolon
          do {
            next = *(iter++);
            if(next.ty != Comma && next.ty != Semicolon){
                if(next.ty == reBracket || next.ty == AddressOp || flag==1){
                        if(next.ty == Register){
                                temp = temp + ".." + next.str + "..";
                        } else {
                                temp = temp + next.str;
                        }
                } else {
                        temp = temp + " " + next.str;
                }    
                if(next.ty == leBracket){
                        flag = 1;
                }
                if(next.ty == reBracket){
                        flag = 0;
                }
            }
          } while (next.ty != Semicolon);
          func.bb[bbIdx].inst.push_back(temp);
        }
	
	} else*/ if (next.ty != Register) {
	  std::cout << "Error with: " << " " << (*(iter-4)).str << " " << (*(iter-3)).str << " " << (*(iter-2)).str << " ..RG.. " << (*(iter-1)).str << " " << next.str << " ..RG.. " << (*(iter)).str << " " << (*(iter+1)).str << " " << (*(iter+2)).str << "\n";
          std::cerr << "Expected Register after Guard token not found!\n";
          return false; 
        }
      }
      // LC Bracket of inline asm
      else if (next.ty == lcBracket) {
	//do {
	  // Skip
	  //next = *(iter++);
	//} while (next.ty == rcBracket);
	//if(*(iter).ty == Guard && *(iter+1).ty == Instruction){
		
	//} else {
        	++cBracketLevel;
	//}
        // Skip
      }
      // rcBracket aka End of Function
      else if (next.ty == rcBracket) {
        if (cBracketLevel <= 0){
          //std::cout << "Extra bracket detected\n";
	  break;
	}
        else {
          --cBracketLevel;
	}
      }
      // Error Otherwise
      else {
        std::cerr << "Unexpected token: " << TokenClassName[next.ty] << "\t"
                  << next.str << '\n';
        return false;
      }
    } while (true);

    // Success
    return true;
  } else {
    return false;
  }
}

std::vector<PTXFunction> parse(std::vector<Token> tokenVec) {
  std::vector<PTXFunction> funcVec;

  auto tokenIter = tokenVec.begin();

  while (tokenIter != tokenVec.end()) {
    // TODO Valitade Stuff outside of kernel functions
    Token current = *(tokenIter++);
    if (current.ty == Directive and
        (current.str == ".entry" or current.str == ".func")) {
      PTXFunction func;
      parseFunction(tokenIter, tokenVec.end(), func);
      funcVec.push_back(func);
    }
  }

  return funcVec;
}

} // namespace mekong

#endif
