sed -e 's|XXHARDWARE|AMDbobcat|g' SNAP_in_template.py > SNAP_in_AMDbobcat.py 
sed -e 's|XXHARDWARE|AMDbulldozer|g' SNAP_in_template.py > SNAP_in_AMDbulldozer.py 
sed -e 's|XXHARDWARE|AMDexcavator|g' SNAP_in_template.py > SNAP_in_AMDexcavator.py 
sed -e 's|XXHARDWARE|AMDjaguar|g' SNAP_in_template.py > SNAP_in_AMDjaguar.py 
sed -e 's|XXHARDWARE|AMDpiledriver|g' SNAP_in_template.py > SNAP_in_AMDpiledriver.py 
sed -e 's|XXHARDWARE|AMDryzen|g' SNAP_in_template.py > SNAP_in_AMDryzen.py 
sed -e 's|XXHARDWARE|AMDsteamroller|g' SNAP_in_template.py > SNAP_in_AMDsteamroller.py 
sed -e 's|XXHARDWARE|broadwell|g' SNAP_in_template.py > SNAP_in_broadwell.py 
sed -e 's|XXHARDWARE|goldmontPlus|g' SNAP_in_template.py > SNAP_in_goldmontPlus.py 
sed -e 's|XXHARDWARE|goldmont|g' SNAP_in_template.py > SNAP_in_goldmont.py 
sed -e 's|XXHARDWARE|haswell|g' SNAP_in_template.py > SNAP_in_haswell.py 
sed -e 's|XXHARDWARE|ivybridge|g' SNAP_in_template.py > SNAP_in_ivybridge.py 
sed -e 's|XXHARDWARE|knl|g' SNAP_in_template.py > SNAP_in_knl.py 
sed -e 's|XXHARDWARE|merom|g' SNAP_in_template.py > SNAP_in_merom.py 
sed -e 's|XXHARDWARE|nehalem|g' SNAP_in_template.py > SNAP_in_nehalem.py 
sed -e 's|XXHARDWARE|sandybridge|g' SNAP_in_template.py > SNAP_in_sandybridge.py 
sed -e 's|XXHARDWARE|silvermont|g' SNAP_in_template.py > SNAP_in_silvermont.py 
sed -e 's|XXHARDWARE|skylake|g' SNAP_in_template.py > SNAP_in_skylake.py 
sed -e 's|XXHARDWARE|skylake-X|g' SNAP_in_template.py > SNAP_in_skylake-X.py 
sed -e 's|XXHARDWARE|wolfdale|g' SNAP_in_template.py > SNAP_in_wolfdale.py 
