python3 ../../ppt.py SNAP_in_AMDbobcat >> AllOutputs.txt 
python3 ../../ppt.py SNAP_in_AMDbulldozer >> AllOutputs.txt 
python3 ../../ppt.py SNAP_in_AMDexcavator >> AllOutputs.txt 
python3 ../../ppt.py SNAP_in_AMDjaguar >> AllOutputs.txt 
python3 ../../ppt.py SNAP_in_AMDpiledriver >> AllOutputs.txt 
python3 ../../ppt.py SNAP_in_AMDryzen >> AllOutputs.txt 
python3 ../../ppt.py SNAP_in_AMDsteamroller >> AllOutputs.txt 
python3 ../../ppt.py SNAP_in_broadwell >> AllOutputs.txt 
python3 ../../ppt.py SNAP_in_goldmontPlus >> AllOutputs.txt 
python3 ../../ppt.py SNAP_in_goldmont >> AllOutputs.txt 
python3 ../../ppt.py SNAP_in_haswell >> AllOutputs.txt 
python3 ../../ppt.py SNAP_in_ivybridge >> AllOutputs.txt 
python3 ../../ppt.py SNAP_in_knl >> AllOutputs.txt 
python3 ../../ppt.py SNAP_in_merom >> AllOutputs.txt 
python3 ../../ppt.py SNAP_in_nehalem >> AllOutputs.txt 
python3 ../../ppt.py SNAP_in_sandybridge >> AllOutputs.txt 
python3 ../../ppt.py SNAP_in_silvermont >> AllOutputs.txt 
python3 ../../ppt.py SNAP_in_skylake >> AllOutputs.txt 
python3 ../../ppt.py SNAP_in_skylake-X >> AllOutputs.txt 
python3 ../../ppt.py SNAP_in_wolfdale >> AllOutputs.txt 
